_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: ja
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    ja: ja
    en: en
    '': null
  domains:
    ja: ''
    en: ''
selected_langcode: site_default
